### ISSUE TITLE
你好，自建mysql使用时，全局图中的有几个不能显示，如下：CPU、内存、磁盘、磁盘io。

### ISSUE THREAD

**Issue by sxlstevengit** [starsliao/multi_mysqld_exporter#1]
你好，自建mysql使用时，全局图中的有几个不能显示，如下：CPU、内存、磁盘、磁盘io。

**Comment by sxlstevengit** [comment]
![image](https://user-images.githubusercontent.com/26913592/206343744-75e6174e-74f9-42f5-8b71-4d7e9b427887.png)

**Comment by starsliao** [comment]
请更新下看板 https://grafana.com/grafana/dashboards/17320-1-mysqld-exporter-dashboard/

昨天更新了看板，支持自建mysql从node-exporter中获取以上信息，通过instance的IP部分进行关联。

**Comment by ZimaBlueee** [comment]
跪求：自建mysql从node-exporter中获取以上信息的教程
