### ISSUE TITLE
您好, 请问下有多个自建mysql的时候, 下面的cpu, 内存, 磁盘使用率都只能读到第一个自建的mysql, 这个应该需要改什么配置吗? 

### ISSUE THREAD

**Issue by k1n9met** [starsliao/multi_mysqld_exporter#2]
![WechatIMG25375](https://github.com/starsliao/multi_mysqld_exporter/assets/20240078/44540acd-a1de-4617-a8fb-4c942748df3a)

![WechatIMG220165](https://github.com/starsliao/multi_mysqld_exporter/assets/20240078/cac76169-b56a-4e0a-a334-5c6896f6a51d)

**Comment by starsliao** [comment]
上面菜单 host选择哪个就显示哪个的明细

**Comment by k1n9met** [comment]
主要是host我选了第二个，但是还是上面图中红圈圈起来的那三项还是第一个的监控

**Comment by starsliao** [comment]
你看下那个图表的promql, 使用的是`node_host`这个变量, 所以你看下下看板的变量`node_host`有没有取到值.按照这个方法来查就行了.

**Comment by k1n9met** [comment]
![WechatIMG25378](https://github.com/starsliao/multi_mysqld_exporter/assets/20240078/529d8134-d912-4311-9ce8-44a12d457307)
![WechatIMG25377](https://github.com/starsliao/multi_mysqld_exporter/assets/20240078/6c5d36cc-684b-4804-80c3-45d82304f80e)

我看了下json文件, node_host这个选项被隐藏了, 所以一直是默认的第一个, 本来想把promql那边$node_host改成$host, 然后用正则替换掉:端口号, 但是好像没函数替换, 所以先把那个hide改成0, 请问下除了这个方法还有什么办法解决吗

**Comment by starsliao** [comment]
node_host 你看看它的promql 实际上是跟名称字段关联的,选择不同的名称会跟着变的, 所以隐藏掉了

**Comment by k1n9met** [comment]
不知道是不是版本的问题, 用的是最新版的, host切换时, node_host是不会改变的

**Comment by starsliao** [comment]
切换名称,不是切换host
![图片](https://github.com/starsliao/multi_mysqld_exporter/assets/3349611/63a2fc11-84bc-42d3-8938-81596b41ed51)

你看关联的变量是name 不是host
![图片](https://github.com/starsliao/multi_mysqld_exporter/assets/3349611/ab0075f9-6587-40df-9568-1de5e36b5fde)

**Comment by k1n9met** [comment]
![1694491549761](https://github.com/starsliao/multi_mysqld_exporter/assets/20240078/1ee632b7-ac55-4fe7-83d1-ec1d2cd834d7)
可能是自建mysql的问题, 是没有name可以选的, 需要云厂商的rds接入才有name的吧

**Comment by starsliao** [comment]
是不是你的prometheus job 没有安装我给的配置来配置,正常的话会有name字段的 ,云rds和自建的做了兼容都是name字段,取的是consul的__meta_consul_service_metadata_name
